[package]
name = "carpoolia"
version = "0.1.0"
authors = ["Nora Björklund <nora@noraply.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
